Repository Shubham0812/Color.Dev_UI, pull requests merged in 2022-10, with the labels that each got.

#4 Task/base architecture
  .DS_Store
  Color.Dev_UI.xcodeproj/project.pbxproj
  Color.Dev_UI/Code/Controllers/Color_Dev_UIApp.swift
  Color.Dev_UI/Code/Features/Main/Views/MainView.swift
  Color.Dev_UI/ContentView.swift
  Color.Dev_UI/Extensions/ColorExtension.swift
  Color.Dev_UI/Extensions/FoundationExtension.swift
  Color.Dev_UI/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Color.Dev_UI/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Color.Dev_UI/Resources/Assets.xcassets/Contents.json
  Color.Dev_UI/Resources/Color-Dev-UI-Info.plist
  Color.Dev_UI/Resources/Preview Content/Preview Assets.xcassets/Contents.json
  Color.Dev_UI/Utils/Colors.swift
Labels: hackoberfest, hacktoberfest-accepted

#6 📝 Add Architecture and Contributors Documentations
  docs/Architecture.md
  docs/CONTRIBUTORS.md
Labels: documentation, hackoberfest, hacktoberfest-accepted

#13 Task/fonts
  .DS_Store
  Color.Dev_UI.xcodeproj/project.pbxproj
  Color.Dev_UI.xcodeproj/xcshareddata/xcschemes/Color.Dev_UI.xcscheme
  Color.Dev_UI/.DS_Store
  Color.Dev_UI/Code/Controllers/Color_Dev_UIApp.swift
  Color.Dev_UI/Code/Features/Convert/Services/ConvertViewModel.swift
  Color.Dev_UI/Code/Features/Convert/Views/ConvertView.swift
  Color.Dev_UI/Code/Features/Main/Views/MainView.swift
  Color.Dev_UI/Resources/.DS_Store
  Color.Dev_UI/Resources/Assets.xcassets/homeBlue.colorset/Contents.json
  Color.Dev_UI/Resources/Color-Dev-UI-Info.plist
  Color.Dev_UI/Resources/Fonts/.DS_Store
  Color.Dev_UI/Resources/Fonts/Nocturne/Nocturne-Serif-Bold.otf
  Color.Dev_UI/Resources/Fonts/Nocturne/Nocturne-Serif-Medium.otf
  Color.Dev_UI/Resources/Fonts/Nocturne/Nocturne-Serif-Regular.otf
  Color.Dev_UI/Resources/Fonts/Nocturne/Nocturne-Serif-SemiBold.otf
  Color.Dev_UI/Resources/Fonts/Ubuntu/.DS_Store
  Color.Dev_UI/Resources/Fonts/Ubuntu/Ubuntu-Bold.ttf
  Color.Dev_UI/Resources/Fonts/Ubuntu/Ubuntu-Light.ttf
  Color.Dev_UI/Resources/Fonts/Ubuntu/Ubuntu-Medium.ttf
  Color.Dev_UI/Resources/Fonts/Ubuntu/Ubuntu-Regular.ttf
  Color.Dev_UI/Utils/Colors.swift
  Color.Dev_UI/Utils/FontManager.swift
Labels: hackoberfest, hacktoberfest-accepted

#14 Add HapticManager singleton
  Color.Dev_UI/Utils/HapticManager.swift
Labels: hackoberfest, hacktoberfest-accepted

#21 Add Custom Image View
  Color.Dev_UI.xcodeproj/project.pbxproj
  ImageView.swift
Labels: hacktoberfest

#22 Implemented HEX to RGB conversion
  Color.Dev_UI.xcodeproj/project.pbxproj
  Color.Dev_UI/Code/Features/Convert/Services/ConvertViewModel.swift
  Color.Dev_UI/Code/Features/Convert/Views/ConvertView.swift
  Color.Dev_UI/Code/Features/Convert/Views/Support Views/ValidatedTextField.swift
  Color.Dev_UI/Extensions/ColorExtension.swift
  Color.Dev_UI/Formatters/HexFormatter.swift
Labels: hacktoberfest, hacktoberfest-accepted
